TOKEN = '2136797405:AAFEfxXTaTWn8ZnC-FaATv76Mx7nidQtiNo'
START = "Hello, my love. it's my wishes front sleep fo you)\npress button /sleep"
STI = ['CAACAgIAAxkBAAEDZHFhpmcQOmftRJ0PRY3cXjlq3YbQ3QAChA8AAnsMOEnOgn5-CS2ltCIE',
       'CAACAgIAAxkBAAEDZHNhpmjB7SjJt8qAKRzn0KmJBm77pQACHgIAAkcVaAm9KRuuMNQJcCIE',
       'CAACAgIAAxkBAAEDZHVhpmjkVHRIUXISHBAJz3DhCKjRrAACGQIAAkcVaAnq7CIaIKV3ECIE',
       'CAACAgIAAxkBAAEDZHdhpmkJL1bN3koelgiW2ESDKNIGcAACHAIAAkcVaAnFbedQt0jiySIE',
       'CAACAgIAAxkBAAEDZHlhpmlG3gp7ymsAAcK4mGZ71bD9mBIAAvsIAAJ5XOIJLLqJMYK2BF8iBA',
       'AACAgIAAxkBAAEDZHthpmmHMpoH_W5tMSHWL1Za5ox2ZQACDwUAAmvEygrkyJuzc2Kf1SIE'
       ]
